CREATE TABLE `application` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `first_name` VARCHAR(255) NOT NULL,
    `middle_name` VARCHAR(255),
    `last_name` VARCHAR(255) NOT NULL,
    `date_of_birth` DATE NOT NULL,
    `marital_status` ENUM('Single', 'Married', 'Separated', 'Divorced', 'Widowed') NOT NULL,
    `address_line1` VARCHAR(255) NOT NULL,
    `address_line2` VARCHAR(255),
    `city` VARCHAR(255) NOT NULL,
    `state` VARCHAR(255) NOT NULL,
    `postal_code` CHAR(5) NOT NULL,
    `ssn_number` VARCHAR(255) NOT NULL,
    `home_phone` CHAR(10) NOT NULL,
    `office_phone` CHAR(10),
    `mobile_phone` CHAR(10) NOT NULL,
    `email_address` VARCHAR(255) NOT NULL,
    `loan_amount` DECIMAL(15, 2) NOT NULL,
    `loan_purpose` ENUM('Debt', 'Educational_Loan', 'Personal_Loan', 'Home_Loan') NOT NULL,
    `description` TEXT,
    `work_experience` INT,
    `annual_salary` DECIMAL(15, 2) NOT NULL,
    `employer_name` VARCHAR(255) NOT NULL,
    `employer_address_line1` VARCHAR(255) NOT NULL,
    `employer_address_line2` VARCHAR(255),
    `employer_city` VARCHAR(255) NOT NULL,
    `employer_state` VARCHAR(255) NOT NULL,
    `employer_postal_code` CHAR(5) NOT NULL,
    `designation` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
